# 2. Peruvian Recycling 

Look at [this article](./readings/recycling_peru.pdf) about encouraging recycling in Peru.  The paper contains two experiments, a "participation study" and a "participation intensity study."  In this problem, we will focus on the latter study, whose results are contained in Table 4 in this problem.  You will need to read the relevant section of the paper (starting on page 20 of the manuscript) in order to understand the experimental design and variables.  (*Note that "indicator variable" is a synonym for "dummy variable," in case you haven't seen this language before.*)

1. In Column 3 of Table 4A, what is the estimated ATE of providing a recycling bin on the average weight of recyclables turned in per household per week, during the six-week treatment period?  Provide a 95% confidence interval.

>The estimated ATE of providing a recycling bin on the average weight of recyclables turned in per household per week is 0.187kg of recyclables. The 95% confidence interval is 0.187 +- 0.032.

2. In Column 3 of Table 4A, what is the estimated ATE of sending a text message reminder on the average weight of recyclables turned in per household per week?  Provide a 95% confidence interval.

>The estimated ATE of sending a text message reminder on the average weight of recyclables turned in per houseshold per week is -0.024kg. The 95% confidence interval is -0.024 +- 0.039.

3. Which outcome measures in Table 4A show statistically significant effects (at the 5% level) of providing a recycling bin?

> Outcomes from column 1-4. This includes Percentage of visits turned in bag, Avg. no of bins turned in per week, Avg. Weight of recyclables turned in per week, and avg market value of recyclables per week.

4. Which outcome measures in Table 4A show statistically significant effects (at the 5% level) of sending text messages?

>None of them are statistically significant.

5. Suppose that, during the two weeks before treatment, household A turns in 2kg per week more recyclables than household B does, and suppose that both households are otherwise identical (including being in the same treatment group).  From the model, how much more recycling do we predict household A to have than household B, per week, during the six weeks of treatment?   Provide only a point estimate, as the confidence interval would be a bit complicated.  This question is designed to test your understanding of slope coefficients in regression.

> I expect household A to have 0.562 kg of reclycing more per week than houssehold B.

6. Suppose that the variable "percentage of visits turned in bag, baseline" had been left out of the regression reported in Column 1.  What would you expect to happen to the results on providing a recycling bin?  Would you expect an increase or decrease in the estimated ATE?  Would you expect an increase or decrease in the standard error?  Explain our reasoning.

> Leaving this out would increase our standard error but not change our ATE. ATE is not changed by covariates since it was randomized beforehand and only depends on the treatment. The covariates help reduce the standard error by giving us more imformation on the subjects and experiment.

7. In column 1 of Table 4A, would you say the variable "has cell phone" is a bad control?  Explain your reasoning.

> Bad controls are controls that impact the outcome. Has cell phone is a bad control if it was measured after the treatment since recycling more could have made people enough money to buy a cell phone. If it was measured before hand it is not a bad control.

8. If we were to remove the "has cell phone" variable from the regression, what would you expect to happen to the coefficient on "Any SMS message"?  Would it go up or down? Explain your reasoning.

> I think the standard error would go up since regression helps us reduce our errors.